{
"Bs":"https://github.com/DarkYasiyaofc/VOICE/blob/main/Bs(tbg).mp3?raw=true",
"Gm":"https://github.com/DarkYasiyaofc/VOICE/blob/main/GM(tbg).mp3?raw=true",
"Gn":"https://github.com/DarkYasiyaofc/VOICE/blob/main/Gn(tbg).mp3?raw=true",
"Hmm":"https://github.com/DarkYasiyaofc/VOICE/blob/main/Hmm(tbg).mp3?raw=true",
"Ponnaya":"https://github.com/DarkYasiyaofc/VOICE/blob/main/Ponnaya(tbg).mp3?raw=true",
"Hi":"https://github.com/DarkYasiyaofc/VOICE/blob/main/hi.mp3?raw=true",
"Mk":"https://github.com/DarkYasiyaofc/VOICE/blob/main/mk.mp3?raw=true",
"Pissuda":"https://github.com/DarkYasiyaofc/VOICE/blob/main/pissuda.mp3?raw=true",
"Hi":"https://github.com/Avishka-web/Av/blob/6796d81430be2c35739929ac846d2dc8cf71c873/hi2.opus",
"Hukapan":"https://github.com/Avishka-web/Av/raw/refs/heads/main/hukapan.mp3",
"Hutto":"https://github.com/Avishka-web/Av/raw/refs/heads/main/hutto.mp3"
}
